### PR TITLE
Add Joint Model

### LINKED ISSUE #101: Add Joint Model
## Detailed Description
We want a model that can predict both satellite imagery and pv yield. 

## Context
While we ultimately just care about the PV output of the model, predicting where the clouds are moving in the satellite imagery should be a good auxiliary task that might help the model learn what is important vs not. 

## Possible Implementation
Add another version of the `Perceiver` that takes two queries, one for the satellite imagery and one for PV output.

### PR DESCRIPTION
**Pull request by jacobbieker**
# Pull Request

## Description

This adds the ability to train a joint model that takes in multiple modalities and outputs both GSP and, optionally, satellite imagery.

This also splits out the dataloader to `nowcasting-dataloader` and adds support for the various positional encodings that that repo can make from https://github.com/openclimatefix/nowcasting_dataloader/pull/2 and https://github.com/openclimatefix/nowcasting_dataloader/pull/6

Things to do left in this PR:

- [ ]  Make it not require Double for all input types
- [ ] Make the calculation of the input dim more flexible
- [ ] Make the linear layer for the GSP post processing more flexible
- [ ] Test outputting HRV and non-HRV Satellite imagery

Fixes #101 

## How Has This Been Tested?

Unit tests

- [ ] No
- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
One immediate thought from reading the description, does this output PV or GSP predictions?

**Comment by jacobbieker** [comment]
> One immediate thought from reading the description, does this output PV or GSP predictions?

GSP predictions, and optionally satellite imagery predictions as well

**Comment by jacobbieker** [comment]
It might be slightly out of date as a lot of things have changed recently, so just trying to bring it up to speed

**Comment by jacobbieker** [comment]
AS of today, the model very nearly works, it takes all the modalities, processes them, and creates a latent representation, failing in the PerceiverIO forward when using the queries with this error:

```
Error executing job with overrides: ['trainer.gpus=0']
Traceback (most recent call last):
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/einops/einops.py", line 382, in reduce
    return recipe.apply(tensor)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/einops/einops.py", line 204, in apply
    init_shapes, reduced_axes, axes_reordering, added_axes, final_shapes = self.reconstruct_from_shape(
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/einops/einops.py", line 150, in reconstruct_from_shape
    raise EinopsError('Expected {} dimensions, got {}'.format(len(self.input_composite_axes), len(shape)))
einops.EinopsError: Expected 3 dimensions, got 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jacob/satflow/satflow/run.py", line 40, in <module>
    main()
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/jacob/satflow/satflow/run.py", line 36, in main
    return train(config)
  File "/home/jacob/satflow/satflow/experiments/train.py", line 84, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 917, in _run
    self._dispatch()
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _dispatch
    self.accelerator.start_training(self)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 995, in run_stage
    return self._run_train()
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1030, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1114, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 109, in advance
    dl_outputs = self.epoch_loop.run(
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 158, in evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 211, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 178, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/nowcasting_utils/models/base.py", line 131, in validation_step
    return self._train_or_validate_step(batch, batch_idx, is_training=False)
  File "/home/jacob/satflow/satflow/models/joint_model.py", line 483, in _train_or_validate_step
    gsp_y_hat = self(x, query=gsp_query)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jacob/satflow/satflow/models/joint_model.py", line 550, in forward
    return self.model.forward(x, mask=mask, queries=query)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/perceiver_pytorch/multi_perceiver_pytorch.py", line 109, in forward
    perceiver_output = self.perceiver.forward(data, mask, queries)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/perceiver_pytorch/perceiver_io.py", line 97, in forward
    latents = self.decoder_cross_attn(queries, context = x)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/perceiver_pytorch/layers.py", line 52, in forward
    return self.fn(x, **kwargs)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/perceiver_pytorch/layers.py", line 137, in forward
    q, k, v = map(
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/perceiver_pytorch/layers.py", line 138, in <lambda>
    lambda t: rearrange(t, "b n (h d) -> (b h) n d", h=h), (q, k, v)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/einops/einops.py", line 452, in rearrange
    return reduce(tensor, pattern, reduction='rearrange', **axes_lengths)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/einops/einops.py", line 390, in reduce
    raise EinopsError(message + '\n {}'.format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "b n (h d) -> (b h) n d".
 Input tensor shape: torch.Size([32, 92, 4, 8]). Additional info: {'h': 1}.
```

Not quite sure how there is the wrong size input, as I don't see where the inputs to the model change that? And that was working on other Perceiver models?

**Comment by jacobbieker** [comment]
The model trains! The issue above was that the query had to have the middle dimensions combined for the querying to work. The model did start learning, so now its time to get it to be a bit more flexible again.

**Comment by JackKelly** [comment]
> The model trains! 

WOOO!  Awesome work, team!

**Pull request closed without merging**
