### PR TITLE
Add Perceiver IO

### PR DESCRIPTION
**Pull request by jacobbieker**
This adds the Perceiver IO model, and data pre/post-processing to work with satflow. This is adapting and copying parts from the official Jax repo: https://github.com/deepmind/deepmind-research/tree/master/perceiver and using https://github.com/lucidrains/perceiver-pytorch

- [x] Add Perceiver IO lightningModule
- [x] Add Fourier position encoding
- [x] Add Image pre-processing
- [x] Add CNN encoder
- [x] Add MetNet preprocessing
- [x] Remove hard-coded numbers
- [x] Add configs
- [x] Add Image post-processing

### CODE REVIEW

**Comment by jacobbieker** [comment]
Another implementation with multi-modality input is here: https://github.com/fac2003/perceiver-multi-modality-pytorch which seems to somewhat match the JAX version.

**Comment by jacobbieker** [comment]
As of now, the Perceiver trains, but doesn't so as well as the MetNet or most the other models, hovering around a MSE of 0.17. I could be getting the output reshaping wrong though as well, and it still is a bit rough. Getting the multi-modality version to work would also probably be better, instead of just concatenating all the timesteps together along the channel dimension.

**Comment by JackKelly** [comment]
Amazing work getting Perceiver IO up-and-running so quickly!

I agree that Perceiver probably won't really start to flex its muscles until we give it multi-modal inputs but that's a shame that it's not doing as well as the other models.  Maybe a CNN front-end would help?  (Sorry if you've already implemented this - I haven't read the code!)

**Comment by jacobbieker** [comment]
Yeah, quite possibly, I'm also thinking of trying to give it bigger context, like MetNet, where I downsample a much larger area so it can see when clouds are coming from outside the area of interest. I haven't tried a CNN frontend, but I'll definitely add that!

**Comment by jacobbieker** [comment]
This is at the point where PerceiverIO trains, has some basic encoders, going to split finishing that up into a different PR, as this one is quite large.

**Pull request merged**
